"""
Flask API server for COVID-19 SEIR Simulation
Includes CSV export functionality.
"""

from flask import Flask, request, jsonify, render_template, Response
import csv
import io

from simulation.seir import run_seir, get_scenario_presets
from simulation.montecarlo import run_monte_carlo
from simulation.sensitivity import run_sensitivity

app = Flask(__name__)


# ── Pages ──────────────────────────────────────────────────────────────────────

@app.route("/")
def index():
    return render_template("index.html")


# ── API Endpoints ──────────────────────────────────────────────────────────────

@app.route("/api/simulate", methods=["POST"])
def simulate():
    """Run a single deterministic SEIR simulation."""
    data = request.get_json()
    try:
        result = run_seir(
            population=int(data["population"]),
            beta=float(data["beta"]),
            sigma=float(data["sigma"]),
            gamma=float(data["gamma"]),
            initial_infected=int(data["initial_infected"]),
            days=int(data["days"]),
        )
        return jsonify({"status": "ok", "data": result})
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 400


@app.route("/api/montecarlo", methods=["POST"])
def montecarlo():
    """Run Monte Carlo replications."""
    data = request.get_json()
    try:
        result = run_monte_carlo(
            population=int(data["population"]),
            beta=float(data["beta"]),
            sigma=float(data["sigma"]),
            gamma=float(data["gamma"]),
            initial_infected=int(data["initial_infected"]),
            days=int(data["days"]),
            replications=int(data.get("replications", 100)),
            noise_level=float(data.get("noise_level", 0.10)),
        )
        return jsonify({"status": "ok", "data": result})
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 400


@app.route("/api/sensitivity", methods=["POST"])
def sensitivity():
    """Run sensitivity analysis on a single parameter."""
    data = request.get_json()
    try:
        result = run_sensitivity(
            population=int(data["population"]),
            beta=float(data["beta"]),
            sigma=float(data["sigma"]),
            gamma=float(data["gamma"]),
            initial_infected=int(data["initial_infected"]),
            days=int(data["days"]),
            target_param=data["target_param"],
            steps=int(data.get("steps", 30)),
        )
        return jsonify({"status": "ok", "data": result})
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 400


@app.route("/api/scenarios", methods=["GET"])
def scenarios():
    """Return available scenario presets."""
    return jsonify({"status": "ok", "data": get_scenario_presets()})


# ── CSV EXPORT NEW ─────────────────────────────────────────────────────────────────

@app.route("/api/export_csv", methods=["POST"])
def export_csv():
    """
    Export simulation results as a clean, formatted CSV.
    Supports deterministic SEIR and Monte Carlo (mean values).
    """
    data = request.get_json()

    try:
        is_mc = data.get("montecarlo", False)

        if is_mc:
            result = run_monte_carlo(
                population=int(data["population"]),
                beta=float(data["beta"]),
                sigma=float(data["sigma"]),
                gamma=float(data["gamma"]),
                initial_infected=int(data["initial_infected"]),
                days=int(data["days"]),
                replications=int(data.get("replications", 100)),
                noise_level=float(data.get("noise_level", 0.10)),
            )
        else:
            result = run_seir(
                population=int(data["population"]),
                beta=float(data["beta"]),
                sigma=float(data["sigma"]),
                gamma=float(data["gamma"]),
                initial_infected=int(data["initial_infected"]),
                days=int(data["days"]),
            )

        output = io.StringIO()
        writer = csv.writer(output)
        metrics = result.get("metrics", {})

        sim_type = "Monte Carlo (Stochastic)" if is_mc else "Deterministic"

        # ── TITLE BLOCK ──────────────────────────────────────────────────────
        writer.writerow(["COVID-19 SEIR EPIDEMIC SIMULATION — RESULTS EXPORT"])
        writer.writerow(["Generated by", "COVID-19 SEIR Simulator · CSEL 303"])
        writer.writerow(["Simulation Type", sim_type])
        writer.writerow([])

        # ── INPUT PARAMETERS ─────────────────────────────────────────────────
        writer.writerow(["INPUT PARAMETERS"])
        writer.writerow(["-" * 40])
        writer.writerow(["Parameter",              "Value",         "Description"])
        writer.writerow(["Population (N)",          f"{int(data['population']):,}",  "Total simulated population"])
        writer.writerow(["Initial Infected (I₀)",   int(data["initial_infected"]),   "Seed infectious cases"])
        writer.writerow(["Simulation Duration",     f"{int(data['days'])} days",      "Length of simulation"])
        writer.writerow(["β (Transmission Rate)",   float(data["beta"]),             "Contacts/day × transmission probability"])
        writer.writerow(["σ (Incubation Rate)",     float(data["sigma"]),            "1 / incubation period"])
        writer.writerow(["γ (Recovery Rate)",       float(data["gamma"]),            "1 / infectious period"])
        if is_mc:
            writer.writerow(["Replications",        int(data.get("replications", 100)), "Number of Monte Carlo runs"])
            writer.writerow(["Noise Level",         f"{int(data.get('noise_level', 0.10) * 100)}%", "Parameter perturbation (Gaussian std dev)"])
        writer.writerow([])

        # ── SUMMARY METRICS ───────────────────────────────────────────────────
        writer.writerow(["SUMMARY METRICS"])
        writer.writerow(["-" * 40])

        if is_mc:
            writer.writerow(["Metric",                  "Mean",                                       "5th Percentile",                              "95th Percentile"])
            writer.writerow(["Basic Reproduction No. (R₀)", metrics.get("R0_mean"),                  "—",                                           "—"])
            writer.writerow(["Peak Infectious",         f"{metrics.get('peak_infected_mean'):,}",     f"{metrics.get('peak_infected_lower'):,}",     f"{metrics.get('peak_infected_upper'):,}"])
            writer.writerow(["Day of Peak",             metrics.get("peak_day_mean"),                 "—",                                           "—"])
            writer.writerow(["Total Infected (Final R)", f"{metrics.get('total_infected_mean'):,}",  "—",                                           "—"])
        else:
            writer.writerow(["Metric",                      "Value",                                  "Notes"])
            writer.writerow(["Basic Reproduction No. (R₀)", metrics.get("R0"),                       "β / γ"])
            writer.writerow(["Peak Infectious",             f"{metrics.get('peak_infected'):,}",      "Highest simultaneous caseload"])
            writer.writerow(["Day of Peak",                 f"Day {metrics.get('peak_day')}",         "Day with most active cases"])
            writer.writerow(["Total Infected (Final R)",    f"{metrics.get('total_infected'):,}",     "Cumulative recovered/removed"])
            writer.writerow(["Herd Immunity Threshold",     f"{metrics.get('herd_immunity_threshold')}%", "(1 − 1/R₀) × 100"])
        writer.writerow([])

        # ── TIME SERIES DATA ──────────────────────────────────────────────────
        writer.writerow(["TIME SERIES DATA"])
        writer.writerow(["-" * 40])

        if is_mc:
            writer.writerow(["Day", "S — Susceptible (mean)", "E — Exposed (mean)", "I — Infectious (mean)", "R — Recovered (mean)",
                              "I Lower 5%", "I Upper 95%"])
            for i in range(len(result["t"])):
                writer.writerow([
                    int(result["t"][i]),
                    round(result["S"]["mean"][i]),
                    round(result["E"]["mean"][i]),
                    round(result["I"]["mean"][i]),
                    round(result["R"]["mean"][i]),
                    round(result["I"]["lower"][i]),
                    round(result["I"]["upper"][i]),
                ])
        else:
            writer.writerow(["Day", "S — Susceptible", "E — Exposed", "I — Infectious", "R — Recovered"])
            for i in range(len(result["t"])):
                writer.writerow([
                    int(result["t"][i]),
                    round(result["S"][i]),
                    round(result["E"][i]),
                    round(result["I"][i]),
                    round(result["R"][i]),
                ])

        output.seek(0)

        return Response(
            output,
            mimetype="text/csv",
            headers={"Content-Disposition": "attachment; filename=seir_results.csv"}
        )

    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 400

# ── Entry Point ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    app.run(debug=True, port=5000)